"""Citation and evidence construction.

A citation is never generated by the model. The model emits only a marker such
as ``[S3]``; this module maps that marker back to the retrieved chunk and emits
the document title, page number and section, so displayed provenance is always
verifiable against the indexed source.
"""

from __future__ import annotations

from typing import Sequence

from .grounding import GroundingReport, extract_markers
from .models import Citation, RetrievedChunk, truncate


def build_citations(
    chunks: Sequence[RetrievedChunk],
    markers: Sequence[str] | None = None,
) -> list[Citation]:
    """Build citations for ``markers`` (or for every supplied chunk)."""
    by_marker = {f"S{index}": chunk for index, chunk in enumerate(chunks, start=1)}
    requested = list(markers) if markers is not None else list(by_marker)

    citations: list[Citation] = []
    seen_markers: set[str] = set()
    for marker in requested:
        marker = marker.strip()
        if not marker or marker in seen_markers:
            continue
        chunk = by_marker.get(marker)
        if chunk is None:
            continue
        seen_markers.add(marker)
        citations.append(_citation_from_chunk(chunk, marker))
    return citations


def _citation_from_chunk(chunk: RetrievedChunk, marker: str) -> Citation:
    data = chunk.chunk
    return Citation(
        chunk_id=data.chunk_id,
        document_id=data.document_id,
        title=data.title,
        filename=data.filename,
        page=data.page,
        section=data.section,
        excerpt=truncate(data.text.strip(), 420),
        score=round(chunk.score, 4),
        marker=marker,
    )


def citations_for_report(
    report: GroundingReport,
    chunks: Sequence[RetrievedChunk],
) -> list[Citation]:
    """Citations for the markers the answer actually used.

    Falls back to the first chunk when the answer cites nothing, so the evidence
    panel still explains what was retrieved.
    """
    if report.valid_markers:
        return build_citations(chunks, report.valid_markers)
    if chunks:
        return build_citations(chunks[:1])
    return []


def evidence_for_chunks(chunks: Sequence[RetrievedChunk]) -> list[Citation]:
    """All retrieved passages as citations, for the evidence panel."""
    return build_citations(chunks)


def format_citation_line(citation: Citation) -> str:
    section = f", {citation.section}" if citation.section else ""
    return f"[{citation.marker}] {citation.title} - p. {citation.page}{section}"


def format_evidence_block(citations: Sequence[Citation]) -> str:
    lines = ["**Evidence**", ""]
    for citation in citations:
        section = f" - {citation.section}" if citation.section else ""
        lines.append(
            f"- **[{citation.marker}]** {citation.title} "
            f"(p. {citation.page}){section}"
        )
        lines.append(f"  {truncate(citation.excerpt, 300)}")
    return "\n".join(lines)


def markers_from_answer(answer: str) -> list[str]:
    return extract_markers(answer)
